name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  schedule: [cron: "0 9 * * 1"] # follows https://github.com/spacelift-io/runner-terraform
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install mise-en-place
        uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
      - name: Run code quality checks
        run: mise run check --jobs 1
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.set-env.outputs.environment-name }}
      environment-url: ${{ steps.set-env.outputs.environment-url }}
      short-sha: ${{ steps.shorten-git-sha.outputs.short-sha }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Shorten Git SHA to the first 7 characters
        id: shorten-git-sha
        run: echo "short-sha=${GITHUB_SHA::7}" >>"$GITHUB_OUTPUT"
        shell: bash
      - name: Set GitHub Actions deployment environment
        id: set-env
        run: |
          if ${{ github.ref_name == 'main' }}; then
            environment_name="github-actions/write"
            environment_url="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          elif ${{ github.ref_type == 'tag' }}; then
            environment_name="github-actions/write"
            environment_url="https://github.com/$GITHUB_REPOSITORY/releases/tag/$GITHUB_REF_NAME"
          else
            environment_name="github-actions/read"
            environment_url="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          fi
          echo "environment-name=$environment_name" >>"$GITHUB_OUTPUT"
          echo "environment-url=$environment_url" >>"$GITHUB_OUTPUT"
      - name: Create annotation for deployment environment
        if: steps.set-env.outputs.environment-name != ''
        run: echo "::notice::Deployment environment ${{ steps.set-env.outputs.environment-name }}"
  build:
    environment:
      name: ${{ needs.setup.outputs.environment-name }}
      url: ${{ needs.setup.outputs.environment-url }}
    runs-on: ubuntu-latest
    needs: [check, setup]
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Configure AWS credentials
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: us-east-1 # ECR Public resources only support us-east-1.
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          role-duration-seconds: 1200
      - name: Log in to AWS ECR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        with:
          registry: public.ecr.aws
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Set up metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          # TODO: Waiting on approval for custom ECR alias br3ndonland (a1j0z0y3 is the default alias).
          images: |
            ghcr.io/${{ github.repository_owner }}/spacelift-runner-terraform
            public.ecr.aws/a1j0z0y3/spacelift-runner-terraform
          flavor: |
            latest=${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
          tags: |
            type=sha
          # Labels are used to set up `--label` options for Buildx and docker/build-push-action.
          # Similarly, annotations set up `--annotation` options.
          # `--label` options will override LABEL directives in the Dockerfile, and there doesn't
          # seem to be a way to select only certain labels to override with docker/metadata-action.
          # Therefore, it's more useful to set labels with docker/metadata-action than with the Dockerfile.
          # https://docs.docker.com/build/ci/github-actions/annotations/
          # https://docs.docker.com/reference/cli/docker/buildx/build/
          # https://github.com/docker/metadata-action/issues/243
          # https://github.com/docker/metadata-action?tab=readme-ov-file#global-expressions
          # https://github.com/docker/build-push-action/blob/9e436ba/src/context.ts#L154-L156
          annotations: |
            org.opencontainers.image.description=Spacelift runner image with additional utilities
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.title=spacelift-runner-terraform
          labels: |
            org.opencontainers.image.description=Spacelift runner image with additional utilities
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.title=spacelift-runner-terraform
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index,manifest
      - name: Build and push spacelift image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: containers/spacelift-runner-terraform.dockerfile
          platforms: linux/amd64 # 1Password CLI (op) does not support Alpine Linux on arm64 (aarch64).
          push: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
